fix: ensure tenant_id matches the tenant a client is registered with
reown-com/push-server pull request #168
Opened 2023-07-27 14:46 UTC by HarryET

# Description

While debugging 5XX errors, I noticed there was a potential to send a notification to a client from another tenant. This shouldn't have been as issue as the `push_message` has signature validation and the relay behaviour should have been within specification. 

## How Has This Been Tested?
Builds locally

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-07-28 13:43 UTC, chris13524 requested changes

2023-07-28 13:43 UTC, chris13524 commented on src/error.rs
> +    MissatchedTenantId,
```suggestion
    MissmatchedTenantId,
```

2023-07-28 14:20 UTC, HarryET commented
I noticed something while making this, we were not settings the `tenant_id` for stored tenants, so for now we need to store for all existing and not change behaviour for past. When we re-build for Push Service, client's won't be able to be migrated so this can be solved there.

2023-08-03 09:11 UTC, arein approved these changes

2023-08-03 12:34 UTC, merged