Fix/duplicated push tokens
reown-com/push-server pull request #196
Opened 2023-09-14 22:25 UTC by geekbrother

# Description

When an app is reinstalled, the device ID (table clients -> column id) is changed, but the token remains the same causing the same token to be inserted for a second device ID as clients -> device_token. 

To make upset for both `id` and `device_token` following changes are made:
- To change the current behavior to upset for both `id` and `device_token` the second `UNIQUE` constraint for `device_token` is added to the SQL migrations. 
- Removing all duplicating `device_token` records and leaving the one recent is implemented as a SQL script in migrations before the `UNIQUE` constraint for `device_token` is added.
- The upset query for the client creation was changed from using `ON CONFLICT` to `DELETE`  and `INSERT` wrapped into a transaction because unfortunately, we can't use `ON CONFLICT` with the exclusion conditions.
- The `client_upsert` functional test was changed to test the new behavior in `create_client` in the following way:
  1. Insert a new client `id` and `device_token` where neither exists, expecting a new row to be added.
  2. Insert a new token with the existing client `id`, expecting `device_token` to be replaced.
  3. Insert new client `id` with same `device_token`, expecting client `id` to be replaced.

Resolves #193

## How Has This Been Tested?

Changes are covered by the `client_upsert` functional test included in this PR.
**To fix the building errors for the `--features functional_tests` flag please apply or cherry-pick the #195 first.**

To test it locally start the PostgreSQL local instances:
```
docker run \
  -p 5432:5432 \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=root \
  -e POSTGRES_DB=postgres \
  --name echo-server-database \
  -d postgres

docker run \
  -p 5433:5433 \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=root \
  -e POSTGRES_DB=postgres \
  --name echo-server-tenant-database \
  -d postgres
```

Build and run the `client_upsert` test:

```
cargo t --features functional_tests functional::stores::client::client_upsert  -- --exact
```

The expected result is `client_upsert` test should pass.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-09-15 07:31 UTC, geekbrother commented
cc @chris13524 we spoke that it's good to test migration scripts as well. 
When invoking the functional tests the [migrations are applied](https://github.com/WalletConnect/echo-server/blob/95474d7a25a8667d129b6660d6a575753ecd938d/tests/context/stores.rs#L26) so these changes seem tested okay by invoking the `functional::stores::client::client_upsert` test.

2023-09-15 08:51 UTC, xav approved these changes
Awesome!

2023-09-15 08:56 UTC, chris13524 requested changes

2023-09-15 08:56 UTC, chris13524 commented on tests/functional/stores/client.rs
> +    // Updating token for the same id
Should each of these scenarios be separate test cases?

2023-09-15 08:56 UTC, chris13524 commented on migrations/1694694520_add_token_unique_constrain.sql
> +ALTER TABLE public.clients
Shouldn't this be within the same transaction as the delete above?

Also, I think we need to only do these migrations in a second PR after the code changes to avoid getting UNIQUE constraint violations?

2023-09-15 12:22 UTC, geekbrother commented on tests/functional/stores/client.rs
> +    // Updating token for the same id
That makes sense, I'll separate them asap and push changes.

2023-09-18 08:48 UTC, geekbrother commented on tests/functional/stores/client.rs
> +    // Updating token for the same id
The test is split into `client_upsert_id` and `client_upsert_token`.

2023-09-18 08:50 UTC, geekbrother commented on migrations/1694694520_add_token_unique_constrain.sql
> +ALTER TABLE public.clients
I think it makes sense, I've extracted the migration to #201 (issue) / #202 (PR) by combining it into the one and wrapping it into a transaction.

2023-09-18 11:21 UTC, chris13524 approved these changes

2023-09-20 13:02 UTC, merged