fix: use `axum-client-ip` to get the real client IP
reown-com/push-server pull request #240
Opened 2023-10-06 21:41 UTC by geekbrother

# Description

This PR adds using of `axum-client-ip` to get a real client IP which is included in the `X-Forwarded` by calling `SecureClientIp`. The AWS ELB[ uses X-Forwarded-for](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html) and [SecureClientIp sourced it for a real IP](https://github.com/imbolc/axum-client-ip/blob/a23f172ee4d01ead9ec25cedd3e6359ba63a03ad/src/secure.rs#L33).

Following changes are made:
 - `axum-client-ip` is added to the `Cargo.toml` as a dependency. We [already have it](https://github.com/WalletConnect/echo-server/blob/46d17972c3f83288fd849ca4c16ad15edb11caee/Cargo.lock#L607) as a relative dependency in the `Cargo.lock` so it will not add additional dependency weight.
 - `ConnectInfo` replaced with `SecureClientIp`.

Resolves #225

## How Has This Been Tested?

Successfully built and run with `analytics` feature enabled.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-10-06 22:08 UTC, chris13524 approved these changes
LGTM

2023-10-06 23:02 UTC, arein commented
Nice vendor agnostic solution!

2023-10-06 23:02 UTC, arein approved these changes

2023-10-07 14:42 UTC, chris13524 requested changes

2023-10-07 14:42 UTC, chris13524 commented on src/lib.rs
> +        .layer(SecureClientIpSource::ConnectInfo.into_extension());
```suggestion
        .layer(SecureClientIpSource::RightmostXForwardedFor.into_extension());
```

2023-10-08 08:26 UTC, geekbrother commented on src/lib.rs
> +        .layer(SecureClientIpSource::ConnectInfo.into_extension());
Good catch! Thanks, Chris. Applied it.

2023-10-08 13:43 UTC, chris13524 approved these changes

2023-10-09 07:19 UTC, merged